version: 0.0
os: linux

files:
  - source: ProductManipulation.war
    destination: /usr/local/tomcat/tomcat/webapps/

hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: root
      permissions: +x

  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
      permissions: +x
